version: '2'

services:
  db:
    restart: 'unless-stopped'
    image: 'mysql/mysql-server:5.6'
    env_file: '.env'
    volumes:
      - 'db:/var/lib/mysql'
  omeka_a11y:
    restart: 'unless-stopped'
    image: 'omeka_a11y:latest'
    ports:
      - '80:80'
    links:
      - 'db'

volumes:
  db:
